### Read all users 
GET http://localhost:3001/users

### Create a new user 
POST http://localhost:3001/users 
Content-Type: application/json

{
    "username": "Charlie", 
    "email": "charlie@example.com", 
    "password": "pass123456"
}

### Update a user
PUT http://localhost:3001/users/1
Content-Type: application/json

{
    "username": "Boohjeeh", 
    "email": "booh@example.com",
    "password": "pass123456"
}

### Delete a user
DELETE http://localhost:3001/users/1

### Trigger centralize error handling middleware